# Dracula Tmux Theme
set -g status on
set -g status-bg colour236
set -g status-fg colour249
set -g message-style fg=colour255,bg=colour89

set -g pane-border-style fg=colour241
set -g pane-active-border-style fg=colour198

set -g status-left '#[fg=colour141,bg=colour236] #S #[default]'
set -g status-right '#[fg=colour141,bg=colour236] %Y-%m-%d %H:%M #[default]'