# Nord Tmux Theme
set -g status on
set -g status-bg colour237
set -g status-fg colour250
set -g message-style fg=colour255,bg=colour31

set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour81

set -g status-left '#[fg=colour110,bg=colour237] #S #[default]'
set -g status-right '#[fg=colour110,bg=colour237] %Y-%m-%d %H:%M #[default]'