# One Dark Tmux Theme
set -g status on
set -g status-bg colour234
set -g status-fg colour248
set -g message-style fg=colour255,bg=colour61

set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour111

set -g status-left '#[fg=colour39,bg=colour234] #S #[default]'
set -g status-right '#[fg=colour39,bg=colour234] %Y-%m-%d %H:%M #[default]'